import streamlit as st
from streamlit.components.v1 import html

st.set_page_config(page_title="Coin Catcher", layout="centered")

HTML_CODE = "\n".join([
"<!DOCTYPE html>",
"<html>",
"<head>",
"<meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=no'>",
"<style>",
"body{margin:0;font-family:sans-serif;background:#111;}",
"#game{width:100%;height:420px;background:#1e1e2f;border-radius:16px;border:3px solid #444;position:relative;overflow:hidden;touch-action:none;}",
"#bag{position:absolute;bottom:10px;font-size:48px;transform:translateX(-50%);animation:float 2s ease-in-out infinite;}",
"@keyframes float{0%{transform:translate(-50%,0);}50%{transform:translate(-50%,-6px);}100%{transform:translate(-50%,0);}}",
".item{position:absolute;font-size:28px;animation:spin 1.2s linear infinite;}",
".bomb{animation:blink 0.4s infinite;}",
"@keyframes spin{from{transform:rotate(0deg);}to{transform:rotate(360deg);}}",
"@keyframes blink{0%,100%{opacity:1;}50%{opacity:0.4;}}",
"#ui{margin-top:8px;display:flex;justify-content:space-between;color:white;font-size:14px;}",
"#overlay{position:absolute;inset:0;background:rgba(0,0,0,.8);display:flex;align-items:center;justify-content:center;flex-direction:column;color:white;z-index:10;}",
"#leaderboard{margin-top:10px;color:white;font-size:14px;}",
".shake{animation:shake .25s;}",
"@keyframes shake{0%{transform:translate(0,0);}25%{transform:translate(-5px,0);}50%{transform:translate(5px,0);}75%{transform:translate(-5px,0);}100%{transform:translate(0,0);}}",
"input,button{padding:6px 10px;font-size:14px;margin-top:6px;}",
"</style>",
"</head>",
"<body>",

"<div id='game'>",
" <div id='bag'>👜</div>",
" <div id='overlay'>",
"  <div id='message'>輸入玩家名稱</div>",
"  <input id='playerName' placeholder='你的名字'>",
"  <div id='nameError' style='color:#f66;font-size:12px;'></div>",
"  <button onclick='registerAndStart()'>開始遊戲</button>",
" </div>",
"</div>",

"<div id='ui'>",
" <div>❤️ <span id='life'>5</span></div>",
" <div>分數 <span id='score'>0</span></div>",
" <div>Lv <span id='level'>1</span></div>",
" <div>⏱ <span id='time'>60</span>s</div>",
"</div>",

"<div id='leaderboard'>",
"<b>🏆 排行榜</b>",
"<ol id='board'></ol>",
"</div>",

"<script>",
"const game=document.getElementById('game');",
"const bag=document.getElementById('bag');",
"const scoreEl=document.getElementById('score');",
"const levelEl=document.getElementById('level');",
"const timeEl=document.getElementById('time');",
"const lifeEl=document.getElementById('life');",
"const overlay=document.getElementById('overlay');",
"const message=document.getElementById('message');",
"const nameInput=document.getElementById('playerName');",
"const nameError=document.getElementById('nameError');",
"const board=document.getElementById('board');",

"let items=[],score=0,timeLeft=60,level=1,life=5,running=false,lastTime=performance.now(),player='';",

"const coins=[",
" {icon:'🪙',value:10,speed:80},",
" {icon:'💰',value:30,speed:100},",
" {icon:'💎',value:50,speed:120}",
"];",
"const bomb={icon:'💣',value:0,speed:150};",

"function loadBoard(){",
" const data=JSON.parse(localStorage.getItem('coinBoard')||'[]');",
" board.innerHTML='';",
" data.slice(0,5).forEach(r=>{",
"  const li=document.createElement('li');",
"  li.textContent=`${r.name} - ${r.score} (Lv${r.level})`;",
"  board.appendChild(li);",
" });",
"}",

"loadBoard();",

"function registerAndStart(){",
" const name=nameInput.value.trim();",
" if(!name){nameError.textContent='請輸入名字';return;}",
" const data=JSON.parse(localStorage.getItem('coinBoard')||'[]');",
" if(data.some(d=>d.name===name)){",
"  nameError.textContent='此名字已被使用，請換一個';return;",
" }",
" player=name;",
" nameError.textContent='';",
" startGame();",
"}",

"function moveBag(x){const r=game.getBoundingClientRect();bag.style.left=Math.max(0,Math.min(r.width,x-r.left))+'px';}",
"game.addEventListener('mousemove',e=>running&&moveBag(e.clientX));",
"game.addEventListener('touchmove',e=>{if(!running)return;e.preventDefault();moveBag(e.touches[0].clientX);},{passive:false});",

"function startGame(){",
" items.forEach(i=>i.el.remove());items=[];",
" score=0;timeLeft=60;level=1;life=5;running=true;",
" scoreEl.textContent=score;timeEl.textContent=timeLeft;levelEl.textContent=level;lifeEl.textContent=life;",
" overlay.style.display='none';lastTime=performance.now();",
" requestAnimationFrame(loop);",
" const t=setInterval(()=>{if(!running){clearInterval(t);return;}timeLeft--;timeEl.textContent=timeLeft;level=Math.floor((60-timeLeft)/20)+1;levelEl.textContent=level;if(timeLeft<=0)endGame();},1000);",
"}",

"function endGame(){",
" running=false;overlay.style.display='flex';",
" message.innerHTML=`🏁 ${player}<br>分數 ${score}`;",
" const data=JSON.parse(localStorage.getItem('coinBoard')||'[]');",
" data.push({name:player,score,level});",
" data.sort((a,b)=>b.score-a.score);",
" localStorage.setItem('coinBoard',JSON.stringify(data));",
" loadBoard();",
"}",

"function spawn(){",
" const isBomb=Math.random()<Math.min(.2+level*.05,.45);",
" const t=isBomb?bomb:coins[Math.floor(Math.random()*coins.length)];",
" const el=document.createElement('div');",
" el.className='item'+(isBomb?' bomb':'');",
" el.textContent=t.icon;",
" el.style.left=Math.random()*90+'%';el.style.top='-30px';",
" game.appendChild(el);",
" items.push({el,isBomb,speed:t.speed+level*15,value:t.value});",
"}",

"function loop(now){",
" if(!running)return;",
" const dt=(now-lastTime)/1000;lastTime=now;",
" if(Math.random()<0.05+level*0.01)spawn();",
" items=items.filter(it=>{",
"  let y=it.el.offsetTop+it.speed*dt;it.el.style.top=y+'px';",
"  const b=bag.getBoundingClientRect(),r=it.el.getBoundingClientRect();",
"  if(r.bottom>=b.top&&r.left<b.right&&r.right>b.left){",
"   if(it.isBomb){life--;lifeEl.textContent=life;game.classList.add('shake');setTimeout(()=>game.classList.remove('shake'),200);if(life<=0){endGame();}}",
"   else{score+=it.value;scoreEl.textContent=score;}",
"   it.el.remove();return false;",
"  }",
"  if(y>450){it.el.remove();return false;}return true;",
" });",
" requestAnimationFrame(loop);",
"}",
"</script>",

"</body>",
"</html>"
])

html(HTML_CODE, height=720)
