import streamlit as st
from streamlit.components.v1 import html

st.set_page_config(page_title="Coin Catcher", layout="centered")

HTML_CODE = "\n".join([
"<!DOCTYPE html>",
"<html>",
"<head>",
"<meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=no'>",
"<style>",
"body{margin:0;font-family:sans-serif;background:#111;}",
"#game{width:100%;height:420px;background:#1e1e2f;border-radius:16px;border:3px solid #444;position:relative;overflow:hidden;touch-action:none;}",
"#bag{position:absolute;bottom:10px;font-size:48px;transform:translateX(-50%);animation:float 2s ease-in-out infinite;}",
"@keyframes float{0%{transform:translate(-50%,0);}50%{transform:translate(-50%,-6px);}100%{transform:translate(-50%,0);}}",
".item{position:absolute;font-size:28px;pointer-events:none;}",
".bomb{filter:drop-shadow(0 0 6px red);}",
".particle{position:absolute;font-size:12px;pointer-events:none;}",
"#ui{margin-top:8px;display:flex;justify-content:space-between;color:white;font-size:14px;}",
"#overlay{position:absolute;inset:0;background:rgba(0,0,0,.8);display:flex;align-items:center;justify-content:center;flex-direction:column;color:white;z-index:10;}",
".shake{animation:shake .25s;}",
"@keyframes shake{0%{transform:translate(0,0);}25%{transform:translate(-5px,0);}50%{transform:translate(5px,0);}75%{transform:translate(-5px,0);}100%{transform:translate(0,0);}}",
"input,button{padding:6px 10px;font-size:14px;margin-top:6px;}",
"</style>",
"</head>",
"<body>",

"<div id='game'>",
"<div id='bag'>👜</div>",
"<div id='overlay'>",
"<div id='message'>輸入玩家名稱</div>",
"<input id='playerName' placeholder='你的名字'>",
"<div id='nameError' style='color:#f66;font-size:12px;'></div>",
"<button onclick='registerAndStart()'>開始遊戲</button>",
"</div>",
"</div>",

"<div id='ui'>",
"<div>❤️ <span id='life'>5</span></div>",
"<div>分數 <span id='score'>0</span></div>",
"<div>Lv <span id='level'>1</span></div>",
"<div>⏱ <span id='time'>60</span>s</div>",
"</div>",

"<script>",
"const game=document.getElementById('game');",
"const bag=document.getElementById('bag');",
"const scoreEl=document.getElementById('score');",
"const levelEl=document.getElementById('level');",
"const timeEl=document.getElementById('time');",
"const lifeEl=document.getElementById('life');",
"const overlay=document.getElementById('overlay');",
"const nameInput=document.getElementById('playerName');",
"const nameError=document.getElementById('nameError');",

"let items=[],score=0,timeLeft=60,level=1,life=5,running=false,lastTime=performance.now(),player='';",

"/* ===== 音效系統 ===== */",
"const AudioCtx=window.AudioContext||window.webkitAudioContext;",
"const audioCtx=new AudioCtx();",
"function playTone(freq,dur,type='sine'){",
" const o=audioCtx.createOscillator();",
" const g=audioCtx.createGain();",
" o.type=type;o.frequency.value=freq;",
" o.connect(g);g.connect(audioCtx.destination);",
" g.gain.setValueAtTime(0.1,audioCtx.currentTime);",
" g.gain.exponentialRampToValueAtTime(0.001,audioCtx.currentTime+dur);",
" o.start();o.stop(audioCtx.currentTime+dur);",
"}",

"function vibrate(ms){ if(navigator.vibrate) navigator.vibrate(ms); }",

"const coins=[",
" {icon:'🪙',value:10,speed:60,freq:500},",
" {icon:'💰',value:30,speed:80,freq:800},",
" {icon:'💎',value:50,speed:100,freq:1100}",
"];",
"const bomb={icon:'💣',speed:120};",

"function moveBag(x){const r=game.getBoundingClientRect();bag.style.left=Math.max(0,Math.min(r.width,x-r.left))+'px';}",
"game.addEventListener('mousemove',e=>running&&moveBag(e.clientX));",
"game.addEventListener('touchmove',e=>{if(!running)return;e.preventDefault();moveBag(e.touches[0].clientX);},{passive:false});",

"function registerAndStart(){",
" const n=nameInput.value.trim();",
" if(!n){nameError.textContent='請輸入名字';return;}",
" player=n;nameError.textContent='';startGame();",
"}",

"function startGame(){",
" items.forEach(i=>i.el.remove());items=[];",
" score=0;timeLeft=60;level=1;life=5;running=true;",
" scoreEl.textContent=score;timeEl.textContent=timeLeft;levelEl.textContent=level;lifeEl.textContent=life;",
" overlay.style.display='none';lastTime=performance.now();",
" requestAnimationFrame(loop);",
" const t=setInterval(()=>{if(!running){clearInterval(t);return;}timeLeft--;timeEl.textContent=timeLeft;level=Math.floor((60-timeLeft)/20)+1;levelEl.textContent=level;if(timeLeft<=0)endGame();},1000);",
"}",

"function endGame(){ running=false; overlay.style.display='flex'; }",

"function spawn(){",
" const isBomb=Math.random()<Math.min(.2+level*.05,.45);",
" const t=isBomb?bomb:coins[Math.floor(Math.random()*coins.length)];",
" const el=document.createElement('div');",
" el.className='item'+(isBomb?' bomb':'');",
" el.textContent=t.icon;",
" el.style.left=Math.random()*90+'%'; el.style.top='-30px';",
" game.appendChild(el);",
" items.push({el,isBomb,t,speed:t.speed+level*15,vy:0,phase:Math.random()*Math.PI*2});",
"}",

"function particles(x,y){",
" for(let i=0;i<6;i++){",
"  const p=document.createElement('div');",
"  p.className='particle';p.textContent='✨';",
"  p.style.left=x+'px';p.style.top=y+'px';",
"  game.appendChild(p);",
"  const dx=(Math.random()-0.5)*60,dy=Math.random()*-60;",
"  p.animate([{transform:'translate(0,0)',opacity:1},{transform:`translate(${dx}px,${dy}px)`,opacity:0}],{duration:500});",
"  setTimeout(()=>p.remove(),500);",
" }",
"}",

"function loop(now){",
" if(!running)return;",
" const dt=(now-lastTime)/1000;lastTime=now;",
" if(Math.random()<0.05+level*0.01)spawn();",
" items=items.filter(it=>{",
"  it.vy+=200*dt;",
"  it.phase+=dt*3;",
"  let y=it.el.offsetTop+it.vy*dt;",
"  let sway=Math.sin(it.phase)*10;",
"  it.el.style.top=y+'px';",
"  it.el.style.transform=`translateX(${sway}px)`;",
"  const b=bag.getBoundingClientRect(),r=it.el.getBoundingClientRect();",
"  if(r.bottom>=b.top&&r.left<b.right&&r.right>b.left){",
"   if(it.isBomb){",
"    life--;lifeEl.textContent=life;playTone(120,0.4,'square');vibrate(200);",
"    game.classList.add('shake');setTimeout(()=>game.classList.remove('shake'),200);",
"    if(life<=0)endGame();",
"   }else{",
"    score+=it.t.value;scoreEl.textContent=score;",
"    playTone(it.t.freq,0.15);vibrate(30);",
"    particles(r.left,r.top);",
"   }",
"   it.el.remove();return false;",
"  }",
"  if(y>450){it.el.remove();return false;}return true;",
" });",
" requestAnimationFrame(loop);",
"}",
"</script>",

"</body>",
"</html>"
])

html(HTML_CODE, height=700)
